queues:
  - first
  - second
redis_url: configfile-redis://localhost:6379
namespace: configfile-redirus
nginx:
  pid: configfile-nginx.pid
  configs_path: configfile-sites-enabled
  http_template: 'listen *:8000;'
  https_template: |
    listen *:8443 ssl;
    ssl_certificate     /usr/share/ssl/certs/localhost/host.cert;
    ssl_certificate_key /usr/share/ssl/certs/localhost/host.key;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
  config_template: |
    ## configfile
    #{upstream}
    server {
      #{listen}
      server_name #{name}.localhost;
      server_tokens off;
      location / {
        proxy_pass http://#{upstream_name};
        #{properties}
      }
    }
  allowed_properties:
    - proxy_send_timeout \d
    - proxy_read_timeout \d