queues:
  - first
  - second
redis_url: configfile-redis://localhost:6379
namespace: configfile-redirus
nginx:
  pid: configfile-nginx.pid
  configs_path: configfile-sites-enabled
  http_template: /path/to/http/tmpl
  https_template: /path/to/https/tmpl
  allowed_properties:
    - proxy_send_timeout \d
    - proxy_read_timeout \d
